# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

In [1]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.7.6


### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

In [2]:
import time
import numpy as np
import urllib.request, json
import sqlite3
import os

### Exercício 1

In [3]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?

list_np = np.arange(0, 1000000, 1)
start_time = time.time()
list_np_1 = (list_np * 2)
print(f'--- {(time.time() - start_time)} segundos ---')

--- 0.00467371940612793 segundos ---


In [4]:
list_py = list(range(0, 1000000, 1))
start_time_1 = time.time()
list_py_1 = (list_py * 2)
print(f'--- {(time.time() - start_time_1)} segundos ---')

--- 0.016635894775390625 segundos ---


### Exercício 2

In [5]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0
array = np.arange(1,11)
array[5:8] = 0
array

array([ 1,  2,  3,  4,  5,  0,  0,  0,  9, 10])

In [6]:
list(range(1, 4, 1))

[1, 2, 3]

### Exercício 3

In [7]:
# Crie um array de 3 dimensões e imprima a dimensão 1 
array_3d = np.array([[list(range(1, 4)), list(range(4, 7))], [list(range(7, 10)), list(range(10, 13))]])

array_3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

### Exercício 4

In [8]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas
lista = [[1,8,2], [0, 4, 9], [2, 7, 3]]

matrx_q4 = np.matrix(lista)
matrx_q4

matrix([[1, 8, 2],
        [0, 4, 9],
        [2, 7, 3]])

In [9]:
# Imprima os elementos da terceira linha da matriz
matrx_q4[2:3]

matrix([[2, 7, 3]])

In [10]:
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas
matrx_q4[:2, 1:3]

matrix([[8, 2],
        [4, 9]])

### Exercício 5

In [11]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
arr.shape

(3, 5)

In [13]:
arr_trans = np.transpose(arr)
arr_trans

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Exercício 6

In [14]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
lista = list()
for n,m in enumerate(cond):
    if m == True:
        lista.append(xarr[n])
    elif m == False:
        lista.append(yarr[n])
print(lista)       

[1.1, 2.2, 1.3, 1.4, 2.5]


### Exercício 7

In [15]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B
A = np.arange(10)
print(A)
np.save('array_a', A)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
B = np.load('array_a.npy')
print(B)

[0 1 2 3 4 5 6 7 8 9]


### Exercício 8

In [17]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])
obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

### Exercício 9

In [18]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

In [19]:
data = resp.json()
data[0]['title']

'Revert "BUG/REG: RollingGroupby MultiIndex levels dropped (#38737)"'

In [31]:
df = pd.DataFrame(data)
df.head()

url  \
0  https://api.github.com/repos/pandas-dev/pandas...   
1  https://api.github.com/repos/pandas-dev/pandas...   
2  https://api.github.com/repos/pandas-dev/pandas...   
3  https://api.github.com/repos/pandas-dev/pandas...   
4  https://api.github.com/repos/pandas-dev/pandas...   

                                   repository_url  \
0  https://api.github.com/repos/pandas-dev/pandas   
1  https://api.github.com/repos/pandas-dev/pandas   
2  https://api.github.com/repos/pandas-dev/pandas   
3  https://api.github.com/repos/pandas-dev/pandas   
4  https://api.github.com/repos/pandas-dev/pandas   

                                          labels_url  \
0  https://api.github.com/repos/pandas-dev/pandas...   
1  https://api.github.com/repos/pandas-dev/pandas...   
2  https://api.github.com/repos/pandas-dev/pandas...   
3  https://api.github.com/repos/pandas-dev/pandas...   
4  https://api.github.com/repos/pandas-dev/pandas...   

                                        comments_url  \
0  https://api.github.com/repos/pandas-dev/pandas...   
1  https://api.github.com/repos/pandas-dev/pandas...   
2  https://api.github.com/repos/pandas-dev/pandas...   
3  https://api.github.com/repos/pandas-dev/pandas...   
4  https://api.github.com/repos/pandas-dev/pandas...   

                                          events_url  \
0  https://api.github.com/repos/pandas-dev/pandas...   
1  https://api.github.com/repos/pandas-dev/pandas...   
2  https://api.github.com/repos/pandas-dev/pandas...   
3  https://api.github.com/repos/pandas-dev/pandas...   
4  https://api.github.com/repos/pandas-dev/pandas...   

                                            html_url         id  \
0    https://github.com/pandas-dev/pandas/pull/39191  787062338   
1  https://github.com/pandas-dev/pandas/issues/39189  787001863   
2    https://github.com/pandas-dev/pandas/pull/39188  786972726   
3    https://github.com/pandas-dev/pandas/pull/39186  786849849   
4    https://github.com/pandas-dev/pandas/pull/39185  786670488   

                            node_id  number  \
0  MDExOlB1bGxSZXF1ZXN0NTU1ODM2NTIy   39191   
1          MDU6SXNzdWU3ODcwMDE4NjM=   39189   
2  MDExOlB1bGxSZXF1ZXN0NTU1NzYzMTY2   39188   
3  MDExOlB1bGxSZXF1ZXN0NTU1NjYxMDE0   39186   
4  MDExOlB1bGxSZXF1ZXN0NTU1NTExNDgy   39185   

                                               title  ...  \
0  Revert "BUG/REG: RollingGroupby MultiIndex lev...  ...   
1  BUG: queries on categorical string columns in ...  ...   
2  REGR: Different results from DataFrame.apply a...  ...   
3    REF: extract classes in pandas/core/describe.py  ...   
4                DOC: set the documentation language  ...   

                                           milestone comments  \
0  {'url': 'https://api.github.com/repos/pandas-d...        0   
1                                               None        0   
2  {'url': 'https://api.github.com/repos/pandas-d...        0   
3                                               None        0   
4                                               None        0   

             created_at            updated_at closed_at author_association  \
0  2021-01-15T17:26:31Z  2021-01-15T17:26:31Z      None             MEMBER   
1  2021-01-15T15:57:44Z  2021-01-15T18:28:40Z      None               NONE   
2  2021-01-15T15:17:31Z  2021-01-15T15:29:32Z      None             MEMBER   
3  2021-01-15T12:12:34Z  2021-01-15T16:30:03Z      None             MEMBER   
4  2021-01-15T07:22:26Z  2021-01-15T07:26:28Z      None             MEMBER   

  active_lock_reason                                       pull_request  \
0               None  {'url': 'https://api.github.com/repos/pandas-d...   
1               None                                                NaN   
2               None  {'url': 'https://api.github.com/repos/pandas-d...   
3               None  {'url': 'https://api.github.com/repos/pandas-d...   
4               None  {'url': 'https://api.github.com/repos/pandas-d...   

                  

### Exercício 10

In [21]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas

In [45]:
os.remove("cap08_q10.db") if os.path.exists("cap08_q10.db") else None

In [46]:
con = sqlite3.connect('cap08_q10.db')

In [47]:
type(con)

sqlite3.Connection

In [48]:
cur = con.cursor()

In [49]:
create_command = 'create table cap08_q10 '\
'(id integer not null, '\
'nome varchar(30) not null, '\
'nascimento  date, '\
"peso decimal(5,2), "\
"altura decimal(3,2), "\
'nacionalidade varchar(30) not null)'

In [50]:
cur.execute(create_command)
con.commit()

In [51]:
insert_command = 'insert into cap08_q10 values (?,?,?,?,?,?)'

In [52]:
values_set = [1, 'Djan', '1987-12-30', '70.4', '1.69', 'Brasil']

In [53]:
cur.execute(insert_command, values_set)
con.commit()

In [54]:
sql_select = 'select * from cap08_q10'

In [55]:
cur.execute(sql_select)

In [56]:
dados = cur.fetchall()

In [57]:
colunas = ['id', 'nome', 'nascimento', 'peso', 'altura', 'nacionalidade']
df = pd.DataFrame(dados, columns=colunas)
df

id  nome  nascimento  peso  altura nacionalidade
0   1  Djan  1987-12-30  70.4    1.69        Brasil

# Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>