# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

In [1]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.7.6


### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

In [2]:
import time
import numpy as np
import urllib.request, json

### Exercício 1

In [3]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?

list_np = np.arange(0, 1000000, 1)
start_time = time.time()
list_np_1 = (list_np * 2)
print(f'--- {(time.time() - start_time)} segundos ---')

--- 0.006661891937255859 segundos ---


In [4]:
list_py = list(range(0, 1000000, 1))
start_time_1 = time.time()
list_py_1 = (list_py * 2)
print(f'--- {(time.time() - start_time_1)} segundos ---')

--- 0.017255067825317383 segundos ---


### Exercício 2

In [5]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0
array = np.arange(1,11)
array[5:8] = 0
array

array([ 1,  2,  3,  4,  5,  0,  0,  0,  9, 10])

In [6]:
list(range(1, 4, 1))

[1, 2, 3]

### Exercício 3

In [7]:
# Crie um array de 3 dimensões e imprima a dimensão 1 
array_3d = np.array([[list(range(1, 4)), list(range(4, 7))], [list(range(7, 10)), list(range(10, 13))]])

array_3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

### Exercício 4

In [8]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas
lista = [[1,8,2], [0, 4, 9], [2, 7, 3]]

matrx_q4 = np.matrix(lista)
matrx_q4

matrix([[1, 8, 2],
        [0, 4, 9],
        [2, 7, 3]])

In [9]:
# Imprima os elementos da terceira linha da matriz
matrx_q4[2:3]

matrix([[2, 7, 3]])

In [10]:
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas
matrx_q4[:2, 1:3]

matrix([[8, 2],
        [4, 9]])

### Exercício 5

In [11]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
arr.shape

(3, 5)

In [13]:
arr_trans = np.transpose(arr)
arr_trans

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Exercício 6

In [14]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
lista = list()
for n,m in enumerate(cond):
    if m == True:
        lista.append(xarr[n])
    elif m == False:
        lista.append(yarr[n])
print(lista)       

[1.1, 2.2, 1.3, 1.4, 2.5]


### Exercício 7

In [ ]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B

### Exercício 8

In [15]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])
obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

### Exercício 9

In [25]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

In [26]:
data = resp.json()
data[0]['title']

'Backport PR #39177 on branch 1.2.x (CI: Pin nbformat to 5.0.8)'

In [27]:
df = pd.DataFrame(data)
df

url  \
0   https://api.github.com/repos/pandas-dev/pandas...   
1   https://api.github.com/repos/pandas-dev/pandas...   
2   https://api.github.com/repos/pandas-dev/pandas...   
3   https://api.github.com/repos/pandas-dev/pandas...   
4   https://api.github.com/repos/pandas-dev/pandas...   
5   https://api.github.com/repos/pandas-dev/pandas...   
6   https://api.github.com/repos/pandas-dev/pandas...   
7   https://api.github.com/repos/pandas-dev/pandas...   
8   https://api.github.com/repos/pandas-dev/pandas...   
9   https://api.github.com/repos/pandas-dev/pandas...   
10  https://api.github.com/repos/pandas-dev/pandas...   
11  https://api.github.com/repos/pandas-dev/pandas...   
12  https://api.github.com/repos/pandas-dev/pandas...   
13  https://api.github.com/repos/pandas-dev/pandas...   
14  https://api.github.com/repos/pandas-dev/pandas...   
15  https://api.github.com/repos/pandas-dev/pandas...   
16  https://api.github.com/repos/pandas-dev/pandas...   
17  https://api.github.com/repos/pandas-dev/pandas...   
18  https://api.github.com/repos/pandas-dev/pandas...   
19  https://api.github.com/repos/pandas-dev/pandas...   
20  https://api.github.com/repos/pandas-dev/pandas...   
21  https://api.github.com/repos/pandas-dev/pandas...   
22  https://api.github.com/repos/pandas-dev/pandas...   
23  https://api.github.com/repos/pandas-dev/pandas...   
24  https://api.github.com/repos/pandas-dev/pandas...   
25  https://api.github.com/repos/pandas-dev/pandas...   
26  https://api.github.com/repos/pandas-dev/pandas...   
27  https://api.github.com/repos/pandas-dev/pandas...   
28  https://api.github.com/repos/pandas-dev/pandas...   
29  https://api.github.com/repos/pandas-dev/pandas...   

                                    repository_url  \
0   https://api.github.com/repos/pandas-dev/pandas   
1   https://api.github.com/repos/pandas-dev/pandas   
2   https://api.github.com/repos/pandas-dev/pandas   
3   https://api.github.com/repos/pandas-dev/pandas   
4   https://api.github.com/repos/pandas-dev/pandas   
5   https://api.github.com/repos/pandas-dev/pandas   
6   https://api.github.com/repos/pandas-dev/pandas   
7   https://api.github.com/repos/pandas-dev/pandas   
8   https://api.github.com/repos/pandas-dev/pandas   
9   https://api.github.com/repos/pandas-dev/pandas   
10  https://api.github.com/repos/pandas-dev/pandas   
11  https://api.github.com/repos/pandas-dev/pandas   
12  https://api.github.com/repos/pandas-dev/pandas   
13  https://api.github.com/repos/pandas-dev/pandas   
14  https://api.github.com/repos/pandas-dev/pandas   
15  https://api.github.com/repos/pandas-dev/pandas   
16  https://api.github.com/repos/pandas-dev/pandas   
17  https://api.github.com/repos/pandas-dev/pandas   
18  https://api.github.com/repos/pandas-dev/pandas   
19  https://api.github.com/repos/pandas-dev/pandas   
20  https://api.github.com/repos/pandas-dev/pandas   
21  https://api.github.com/repos/pandas-dev/pandas   
22  https://api.github.com/repos/pandas-dev/pandas   
23  https://api.github.com/repos/pandas-dev/pandas   
24  https://api.github.com/repos/pandas-dev/pandas   
25  https://api.github.com/repos/pandas-dev/pandas   
26  https://api.github.com/repos/pandas-dev/pandas   
27  https://api.github.com/repos/pandas-dev/pandas   
28  https://api.github.com/repos/pandas-dev/pandas   
29  https://api.github.com/repos/pandas-dev/pandas   

                                           labels_url  \
0   https://api.github.com/repos/pandas-dev/pandas...   
1   https://api.github.com/repos/pandas-dev/pandas...   
2   https://api.github.com/repos/pandas-dev/pandas...   
3   https://api.github.com/repos/pandas-dev/pandas...   
4   https://api.github.com/repos/pandas-dev/pandas...   
5   https://api.github.com/repos/pandas-dev/pandas...   
6   https://api.github.com/repos/pandas-dev/pandas...   
7   https://api.github.com/repos/pandas-dev/pandas...   
8   https://api.github.com/repos/pandas-dev/pandas...   
9   https://api.github.com/repos/pand

### Exercício 10

In [ ]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas

# Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>